name: JeyDotC - Blog
markdown: redcarpet
pygments: true
name: JeyDotC
url: http://jeydotc.github.io/
domain: jeydotc.github.io
author :
  name : Jeysson Guevara
  email : jeydotc@gmail.com
  github : https://github.com/JeyDotC
  twitter : https://twitter.com/JeyDotC
