name: JeyDotC - Blog
description: Telling programming adventures :p
keywords: PHP, JavaScript, C#
thumbnail: http://jeydotc.github.io/img/home-background.jpg

markdown: redcarpet
pygments: true
url: http://jeydotc.github.io/
domain: jeydotc.github.io

author :
  name : Jeysson Guevara
  email : jeydotc@gmail.com
  github : https://github.com/JeyDotC
  twitter : https://twitter.com/JeyDotC
  
addThis:
    pubid: ra-53a9b93d3f9d058a